export enum ENV {
  PORT = 'PORT',

  IS_PRODUCTION = 'IS_PRODUCTION',

  CLIENT_URL = 'CLIENT_URL',

  CORS_ORIGIN = 'CORS_ORIGIN',
  CORS_HEADERS = 'CORS_HEADERS',
  CORS_CREDENTIALS = 'CORS_CREDENTIALS',

  DATABASE_URL = 'DATABASE_URL',

  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_VERIFICATION_TOKEN_SECRET = 'JWT_VERIFICATION_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  JWT_VERIFICATION_TOKEN_EXPIRATION_TIME = 'JWT_VERIFICATION_TOKEN_EXPIRATION_TIME',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

  MAILGUN_DOMAIN = 'MAILGUN_DOMAIN',
  MAILGUN_KEY = 'MAILGUN_KEY',
  EMAIL_SEND_FROM = 'EMAIL_SEND_FROM',

  GIANT_BOMB_API_URL = 'GIANT_BOMB_API_URL',
  GIANT_BOMB_API_KEY = 'GIANT_BOMB_API_KEY',

  LEMONSQUEEZY_API_URL = 'LEMONSQUEEZY_API_URL',
  LEMONSQUEEZY_API_KEY = 'LEMONSQUEEZY_API_KEY',
  LEMONSQUEEZY_STORE_ID = 'LEMONSQUEEZY_STORE_ID',
  LEMONSQUEEZY_WEBHOOK_SIGNATURE = 'LEMONSQUEEZY_WEBHOOK_SIGNATURE',

  OPENAI_API_KEY = 'OPENAI_API_KEY',
}
